- name: copy /etc/pam.d/common-session
  copy:
    src: /etc/pam.d/common-session
    dest: /etc/pam.d/common-session
- name: copy /etc/ldap.conf
  copy:
    src: /etc/ldap.conf
    dest: /etc/ldap.conf
- name: copy /etc/ldap/ldap.conf
  copy:
    src: /etc/ldap/ldap.conf
    dest: /etc/ldap/ldap.conf
- name: copy pem
  copy:
    src: /etc/ssl/certs/ca_server.pem
    dest: /etc/ssl/certs/ca_server.pem
- name: copy /etc/nsswitch.conf
  copy:
    src: /etc/nsswitch.conf
    dest: /etc/nsswitch.conf
